import { NgModule } from '@angular/core';
import {
    MatInputModule,
    MatCheckboxModule,
    MatRadioModule,
    MatSelectModule,
    MatAutocompleteModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatSliderModule,
    MatProgressBarModule,
    MatSnackBarModule,
    MatTabsModule,
    MatTooltipModule,
    MatCardModule,
    MatIconModule,
    MatGridListModule,
    MatSidenavModule,
    MatMenuModule,
    MatTableModule,
    MatListModule,
    MatPaginatorModule,
    MatSortModule,
    MatBadgeModule,
    MatBottomSheetModule,
    MatDialogModule,
    MatProgressSpinnerModule
} from '@angular/material';

@NgModule({
    imports: [
        MatInputModule,
        MatCheckboxModule,
        MatRadioModule,
        MatSelectModule,
        MatAutocompleteModule,
        MatButtonModule,
        MatButtonToggleModule,
        MatSliderModule,
        MatProgressBarModule,
        MatSnackBarModule,
        MatTabsModule,
        MatTooltipModule,
        MatCardModule,
        MatIconModule,
        MatGridListModule,
        MatSidenavModule,
        MatMenuModule,
        MatTableModule,
        MatListModule,
        MatPaginatorModule,
        MatSortModule,
        MatBadgeModule,
        MatBottomSheetModule,
        MatDialogModule,
        MatProgressSpinnerModule
    ],
    declarations: [
    ],
    exports: [
        MatInputModule,
        MatCheckboxModule,
        MatRadioModule,
        MatSelectModule,
        MatAutocompleteModule,
        MatButtonModule,
        MatButtonToggleModule,
        MatSliderModule,
        MatProgressBarModule,
        MatSnackBarModule,
        MatTabsModule,
        MatTooltipModule,
        MatCardModule,
        MatIconModule,
        MatGridListModule,
        MatSidenavModule,
        MatMenuModule,
        MatTableModule,
        MatListModule,
        MatPaginatorModule,
        MatSortModule,
        MatBadgeModule,
        MatBottomSheetModule,
        MatDialogModule,
        MatProgressSpinnerModule
    ]
})

export class AngularMaterialModule {}